//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delas.Model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int Id { get; set; }
        public int IdAccount { get; set; }
        public string Title { get; set; }
        public double Amount { get; set; }
        public string OperationType { get; set; }
        public string DestinationAccount { get; set; }
        public double Balance { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
